# Generated by Django 5.1.2 on 2024-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
                ('pages', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('inventer', models.CharField(max_length=255)),
                ('filing_date', models.DateField()),
                ('applicant_name', models.CharField(max_length=255)),
                ('patent_number', models.CharField(max_length=100)),
                ('relevancy', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
